# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9cd8ff8e7c051bcfcd67e0d5d3b11d42bf95c69b66639d1006f1cfe01462189dac1ac47e671e0b044a344ea12901bb59b913d0e7155baf1d8c04f731de098bc

test:
  secret_key_base: 172a0e1f28348317a029c3bd99e87724e23128bef98060a9be2b5a54de013a13601b242163cecf4358d7193356586b53051df78f4f00d8107698173f2adeb9eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
